### ISSUE TITLE
Do you want to execute it? 를 묻지 않고 바로 마이그레이션 진행할 수 있는 옵션 제공

### ISSUE THREAD

**Issue by gaejabong** [xpressengine/plugin-importer#9]
회원 수가 많거나 게시물, 첨부 파일 등이 많은 경우 마이그레이션에 오랜 시간이 소모될 수 있습니다. 이때는 터미널의 접속이 끊기지 않도록 ```nohup``` 같은 명령어를 사용해야 할 것 같은데 현재는 반드시 prompt에서 응답을 해야하기 때문에 사용이 어렵네요. -y 같은 옵션을 제공해서 무조건 마이그레이션을 실행할 수 있다면 좋겠습니다.

**Comment by woongbin** [comment]
--y 옵션을 추가했습니다.

**Comment by gaejabong** [comment]
감사합니다.
